config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('posts/index')

  resources :posts

end

app/models/authoring.rb
class Authoring < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/blogging.rb
class Blogging < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :posts
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :author, :class_name => "User", :foreign_key => :user_id
  belongs_to :parent_post, :class_name => "Post", :foreign_key => :post_id, inverse_of: :comments

end

app/models/commment.rb
class Commment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :category
  has_many :comments, dependent: :destroy, inverse_of: :parent_post
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  has_many :post_authorings, :class_name => "UserPost", dependent: :destroy
  has_many :authors, :through => :post_authorings, :source => :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, :through => :post_tags

end

app/models/post_tag.rb
class PostTag < ApplicationRecord

  belongs_to :post
  belongs_to :tag

  validates :post_id, :uniqueness => { :scope => :tag_id }

end

app/models/post_tags.rb
class PostTags < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/post_user.rb
class PostUser < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/posting.rb
class Posting < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord

  belongs_to :post
  belongs_to :tag
  validates :post_id, :uniqueness => {:scope => :tag_id}

end

app/models/posttag.rb
class Posttag < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/pt.rb
class Pt < ActiveRecord::Base

  belongs_to :post
  belongs_to :tag

end

app/models/pu.rb
class Pu < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :post_tags, dependent: :destroy 
  has_many :tagged_posts, through: :post_tags, source: :post
  has_many :authors_of_tagged_posts, :through => :tagged_posts, :source => :authors

end

app/models/tag_post.rb
class TagPost < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/tagging.rb
class Tagging < ApplicationRecord

  belongs_to :post
  belongs_to :tag

end

app/models/user.rb
class User < ApplicationRecord

  has_many :authored_comments, :class_name => "Comment", :dependent => :destroy
  has_many :post_authorings, :class_name => "UserPost", dependent: :destroy
  has_many :authored_posts, :through => :post_authorings, :source => :post
  has_many :tags_on_authored_posts, :through => :authored_posts, :source => :tags

end

app/models/user_post.rb
class UserPost < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, :uniqueness => { :scope => :post_id }

end

app/models/userpost.rb
class Userpost < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/views/shared/_comment_form.html.erb
<%= post_fields.fields_for :comments do |comment_fields| %>
  <br>
  <%= comment_fields.label :body %>
  <%= comment_fields.text_field :body %>
  <% if comment_fields.object.persisted? %>
    <%= comment_fields.label :delete %>
    <%= comment_fields.check_box :_destroy %>
  <% end %>
  <br>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <p>Aye look bloke, we've got problems:</p>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, messages| %>
  <% messages.each do |message| %>
    <strong><%= message_type %>! <%= message %></strong>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% obj.errors.full_messages.each do |msg| %>
  <p class="danger text-center"><%= msg %></p>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <ul style="list-style: none">
    <li><%= link_to "Post List", posts_path %>
    <li><%= link_to "New Post", new_post_path %>
  </ul>
</nav>

app/views/shared/_post.html.erb
<%= form_for @post do |f| %>

  <%= f.text_field :title %>
  <br>
  <%= f.text_area :body %>
  <br>

  <%= f.collection_check_boxes( :tag_ids, 
                              Tag.all,
                              :id,
                              :name ) %>

  <br>

   <%= f.collection_radio_buttons( :category_id, Category.all, :id, :name ) %> 

  <br>

  <%= f.fields_for :comments do |comment_fields| %>
    <%= comment_fields.label :body, "Add comment" %><br>
    <%= comment_fields.text_area :body %>
    <% if comment_fields.object.persisted? %>
      <%= comment_fields.label :_destroy, "Delete" %>
      <%= comment_fields.check_box :_destroy %>
    <% end %>
    <br>
  <% end %>

  <%= f.submit "#{new_or_edit}" %>

<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post do |post_fields| %>
  <%= post_fields.label :title %>
  <%= post_fields.text_field :title %>
  <%= post_fields.label :body %>
  <%= post_fields.text_field :body %>
  <br>
  <%= post_fields.collection_radio_buttons(:category_id,Category.all,:id,:name) %>
  <br>
  <%= post_fields.collection_select(:category_id,Category.all,:id,:name) %>
  <h3>Combo-box</h1>
  <%= post_fields.collection_select(:tag_ids,Tag.all,:id,:name, {}, multiple: true, class: 'blue') %>
  <%= post_fields.collection_check_boxes(:tag_ids,Tag.all,:id,:name, class: 'blue') %>

  <%= label_tag 'Empty Checkbox' %>
  <%= check_box_tag("post[tag_ids]", []) %>


  <h3>Comment text_field</h3>
  <%= render partial: 'shared/comment_form', locals: { post_fields: post_fields } %>

  <%= post_fields.submit %>
<% end %>




<!-- <h1>Second form</h1> -->
<%#= form_tag posts_path do %>
  <%#= label_tag 'title' %>
  <%#= text_field_tag('post[title]', @post.title) %>
  <%#= label_tag 'body' %>
  <%#= text_field_tag('post[body]', @post.body) %>
  <%#= select_tag "post[category_id]",
  options_for_select(@category_options, @post.category_id) %>
  <%#= submit_tag "Submit other form" %>
<%# end %>